In [1]:
from PyPDF2 import PdfFileReader
import os
import json
import pandas as pd

Extract information from pdf file

In [2]:
def extract_pdf(path):
    pdf=PdfFileReader(path, strict=False)
    number_pages=pdf.getNumPages()
    content=''
    for i in range(number_pages):
        content+=pdf.getPage(i).extractText()
    
    content=content.replace('\n','. ').replace('\n\n','. ')
    content=content.replace('\t',' ')
    
    return content

Get path to each pdf file stored in folder

In [3]:

def get_path_pdf(path_folder):
    path_pdf=[]
    for dirname,_,filenames in os.walk(path_folder):
        for filename in filenames:
            path_pdf.append(os.path.join(dirname,filename))
    return path_pdf

Read JD

In [4]:
path_JD="./static/files_JD/"
path_2_pdfJD=get_path_pdf(path_JD)
content_JD=extract_pdf(path_2_pdfJD[0])

Read CV

In [5]:
path_CV="./static/files_CV/"
path_2_pdfCV=get_path_pdf(path_CV)
content_CV=[]
for p in path_2_pdfCV:
    content_CV.append(extract_pdf(p))

Using Spacy to extract skill

In [6]:
from spacy.pipeline import EntityRuler
from spacy import displacy
import jsonlines
import spacy
import re 
import pyperclip
from sympy import true

In [7]:
json_path="skill_paterns.jsonl"

with jsonlines.open(json_path) as f:
    entities=[line["label"].upper() for line in f.iter()]

# spacy model
nlp=spacy.load("en_core_web_lg")

In [8]:
ruler = nlp.add_pipe("entity_ruler")
ruler.from_disk(json_path)

In [9]:
doc=nlp(content_CV[0])

In [10]:
for sent in (list(doc.sents)):
    tmp=sent.text.split(" ")
    for wolrd in tmp:
        wolrd=wolrd.lower()
        if(wolrd=='experience'):
            print(sent)
            print('===')

PERSONAL INFORMATION

In [11]:

def get_skill(content_CV):
    doc=nlp(content_CV)
    skill_list=[]
    for ent in doc.ents:
        if ent.label_=='SKILL':
            skill_list.append(ent.text)
    skill_list=list(set(skill_list))
    return skill_list

def get_GPA(content_CV):
    doc=nlp(content_CV)
    sent=list(doc.sents)
    gpa=''
    for s in sent:
        s=s.text
        if s.find('GPA') !=-1 :
            gba_pos= s.find('GPA') 
            for i in range (gba_pos+3,gba_pos+8):
                if (s[i] >'0' and s[i]<'9' or s[i]=='.'):
                    gpa+=s[i]
    if gpa=='':
        return None
    else:
        return gpa

def get_experience(content_CV):
    '''
    Return\n
        None if no experience\n
        List of experience if exist
    '''
    doc=nlp(content_CV)
    sent=list(doc.sents)
    final_res=''
    ex=[]
    for s in sent:
        s_text=s.text.split(' ')
        flag=False
        for i in s_text:
            i=i.lower()
            if i=='experience':
                flag=True
        if flag==True:
            ex.append([s.text])
    if (len(ex)==0):
        final_res=None
    else:
        final_res=ex
    return final_res

def get_education(content_CV):
    doc=nlp(content_CV)
    sent=list(doc.sents)
    edu=''
    pos_edu=-1
    pos_edu_end=-1
    for s in sent:
        s_text=s.text.lower()
        flag=False
        if s_text.find('education')!=-1 or s_text.find('university')!=-1 or s_text.find('academic')!=-1 or s_text.find('bachelor ')!=-1:
            edu =s.text
            if s_text.find('education')!=-1 :
                pos_edu=s_text.find('education')+9
            if s_text.find('academic') !=-1 :
                pos_edu=s_text.find('academic')
            if s_text.find('university') !=-1 :
                pos_edu=s_text.find('university')
            else:
                pos_edu=s_text.find('bachelor ')
            
            pos_edu_end=s_text.find('. ',pos_edu)
            edu=edu[pos_edu:pos_edu_end]
    if edu=='':
        return None
    else:
        return edu

def get_phone(content_CV):
    '''
    Format for Phone-Numbers:
    134567890
    123-456-7890
    (123)(456)(7890)
    123.456.7890
    (123)(456-7890)
    '''
    phone= re.compile(r'''
        (\d{3}|\(\d{3}\))    
        (\s|-|\.)?           
        (\d{3}|\(\d{3}\))    
        (\s|-|\.)?           
        (\d{4}|\(\d{4}\))    
    ''', re.VERBOSE) 

    matchs=phone.finditer(content_CV)
    res = ''
    for match in matchs:
        res+=match.group(0)
    if res=='':
        return None
    else:
        return res

def get_link(link,content_CV):
    matchs=link.finditer(content_CV)
    res=''
    for match in matchs:
        res+=match.group(0)
    if res=='':
        return None
    else:
        return res

NAME

In [12]:
from spacy.tokens import Span
import dateparser
def expand_person_entities(doc):
    new_ents = []
    for ent in doc.ents:
        # Only check for title if it's a person and not the first token
        if ent.label_ == "PERSON":
            if ent.start != 0:
                # if person preceded by title, include title in entity
                prev_token = doc[ent.start - 1]
                if prev_token.text in ("Dr", "Dr.", "Mr", "Mr.", "Ms", "Ms."):
                    new_ent = Span(doc, ent.start - 1, ent.end, label=ent.label)
                    new_ents.append(new_ent)
                else:
                    # if entity can be parsed as a date, it's not a person
                    if dateparser.parse(ent.text) is None:
                        new_ents.append(ent) 
        else:
            new_ents.append(ent)
    doc.ents = new_ents
    return doc

# Add the component after the named entity recognizer
# # nlp.remove_pipe('expand_person_entities')
# @Language.component("expand_person_entities")
# nlp.add_pipe("expand_person_entities", after='ner')

# doc = nlp(content_CV[0])
# [(ent.text, ent.label_) for ent in doc.ents if ent.label_=='PERSON']

In [13]:
from spacy.matcher import Matcher
# initialize matcher with a vocab

def extract_name(content_CV):
    matcher = Matcher(nlp.vocab)
    doc=nlp(content_CV)
    error_key=['city','school','university','freelancer','building']
    warning_key=['curriculum vita']
    cut_pos=-1
    # Fisrt way: using ner in spacy
    for ent in doc.ents:
        if ent.label_=='PERSON':
            txt=ent.text
            txt_lower=txt.lower()
            flag=True
            for i in error_key:
                if i in txt_lower:
                    flag=False
            for j in warning_key:
                if j in txt_lower:
                    cut_pos=txt_lower.find(j)
                    txt=txt[:cut_pos]
            if flag==True:
                return txt
            else:
                break
    # Second way: First name and Last name are always Proper Nouns
    pattern = [
        {'POS': 'PROPN'},{'POS': 'PROPN'},
        ]

    matcher.add('NAME',[pattern])
    matches = matcher(doc)
    for match_id, start, end in matches:
        span = doc[start:end]
        return span.text
    return None

extract_name(content_CV[5])

'lÃ  sinh'

Check Accuracy of name

In [14]:
# train_data = json.load(open('./data/training/train_data.json','rb')) 

def name_acc(train_data):
    list_an=[]
    list_txt=[]
    name=[]

    for text,annotation in train_data:
        list_an.append(list(annotation.values()))
        list_txt.append(text)

    target_name=[]
    predic_name=[]

    similar=0
    for i in range(len(list_an)):
        t=''
        p=''
        p=extract_name(list_txt[i])
        predic_name.append(p)
        for j in range(len(list_an[i][0])):
            if list_an[i][0][j][2]=='Name':
                t=list_txt[i][list_an[i][0][j][0]:list_an[i][0][j][1]]
                target_name.append(t)
        if t==p:
            similar+=1
    return (similar/len(list_an)*100)    
# name_acc(train_data)

Load accuracy name

In [15]:
nlp_model=spacy.load('nlp_model')

Using sklearn to calculate the cosine similarity score of CV and JD

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

Cleaning data

In [17]:
def cosine_similar(list_CV,JD):
    df_rank_match=pd.DataFrame(columns=['ID','Percent_Match_JD'])
    for i in range(len(list_CV)):
        test=[list_CV[i],JD]
        cv = CountVectorizer()
        count_matrix= cv.fit_transform(test)
        match=cosine_similarity(count_matrix)        
        row = {
            'ID':i,
            'Percent_Match_JD': round(match[0][1]*100,2)
        }
        new_df=pd.DataFrame([row])
        df_rank_match=pd.concat([df_rank_match,new_df],axis=0,ignore_index=True)
    return df_rank_match

Final extract and save to dataframe

In [21]:
def extract_all_data(list_content_CV,content_JD):
    df_match=cosine_similar(list_content_CV,content_JD)
    extract_df_match=df_match["Percent_Match_JD"]

    label=['ID','Email','Phone_Number','Related_Link','Skill','Experience','Education','GPA']

    df_information = pd.DataFrame(columns=label) 
    # bitbucket
    mail = re.compile(r'[a-zA-Z0-9-\.]+@[a-zA-Z-\.]*\.(com|edu|net|vn)')
    
    git = re.compile(r'(gitlab.com/|github.com/)+[a-zA-Z0-9-\.]*')
    web = re.compile(r'(http://|https:// )+[a-zA-Z0-9-"/"-\.]*')
    linkedin = re.compile(r'linkedin.com/+[a-zA-Z0-9-"/"-\.]*')

    for i in range(len(list_content_CV)):
        content=list_content_CV[i]
        link=[]
        link.append(get_link(git,content))
        link.append(get_link(web,content))
        link.append(get_link(linkedin,content))
        
        row={
                'ID':i,
                # 'Name':extract_name(content),
                'Email':get_link(mail,content),
                'Phone_Number':get_phone(content),
                'Related_Link':link,
                'Skill':get_skill(content),
                'Experience':get_experience(content),
                'Education':get_education(content),
                # 'GPA':get_GPA(content)
            }
        new_df=pd.DataFrame([row])
        df_information=pd.concat([df_information,new_df],axis=0,ignore_index=True)
    df_information=df_information.join(extract_df_match)
    df_information=df_information.sort_values(by='Percent_Match_JD', ascending=False)
    return df_information


# list_CV=[]
# count=0
# train_data = json.load(open('./data/training/train_data.json','rb')) 

# for text,annotation in train_data:
#     count+=1
#     list_CV.append(text)
#     if count==50:
#         break

df_detail=extract_all_data(content_CV,content_JD)

# Modify the column widths to fit the contents
pd.set_option("display.max_colwidth", None)
df_detail

,ID,Email,Phone_Number,Related_Link,Skill,Experience,Education,GPA,Percent_Match_JD
3,3,nghiem0859774418@gmail.com,08597744180859774418,"[github.com/TruongChiNghiem1., http://dentistrychinghiem.tk/., None]","[Laravel, MySQL, Ranking, PHP, schedule]",[[knowledge and experience to become an official.]],None,NaN,42.81
17,17,None,876559927381150312538765599273876559927387655992738765599273,"[None, None, None]","[shrinkage, design, Engineering, Documentation, mode, Languages, software, Simulation, First Class, 3D, Software, Specification, component]",None,"Bachelor in Mechanical Engineering, Seth Sriniwas Agarwal Institute of Engineering & Technology (U.P.T.U) ,",NaN,41.07
20,20,cbt270801@gmail.com,0972707663,"[github.com/BaoThai0605., None, None]","[design, SQL, Framework, Firebase, software engineering, Javascript, PHP, C, Certificate, MongoDB]",None,University,NaN,37.16
31,31,tranhieukhoa442001@gmail.com,None,"[gitlab.com/tranhieukhoa.github.com/hiukhoago, None, linkedin.com/in/k.]","[SQL, React Native, CERTIFICATE, CSS, mobile, certificate, design, Flutter, Trello, GitLab, database, User interface, Laravel, framework, Bootstrap, Design, HTML, Figma, MySQL, Git, API, PHP, Tailwind CSS, GitHub, MongoDB]","[[working hard to learn f rom internet and experience form .], [EXPERIENCE .]]",None,NaN,36.40
1,1,vutammcpe@gmail.com,0352967123,"[None, None, None]","[Algorithms, ASP.NET, PHP, Computer Science, languages, Python, play]",[[- Acquired communication and problem-solving skillsWork experience Objectives .]],University,NaN,35.09
6,6,quanlh0606@gmail.com,None,"[None, None, None]","[SQL, MYSQL, Software Engineering, .NET, PHP, C, Software, CSS, HTML, user interface]",None,University of Education (2019 - Present),NaN,33.82
27,27,letanphuc142001@gmail.com,0829069600,"[github.com/ltphuc2001.github.com/ltphuc2001github.com/ltphuc2001, http://ltpbookstore.epizy.com/., None]","[design, Laravel, SQL, GitHub, Programming Language, MySQL, Jquery, Javascript, Database, Computer Science, PHP, CSS, Ajax, HTML, Python, algorithms, data structures]",[[Learn a lot of experience from the forerunners.]],University HCM City,NaN,30.70
30,30,ngnglinhbao@gmail.com,6142439564,"[github.com/nglinhbaoContactgithub.com/nglinhbaogithub.com/nglinhbaogithub.com/minhpggithub.com/nglinhbao, None, None]","[MySQL, Machine Learning, PHP, Computer Science, CSS, HTML, Python, algorithms, Ruby]",None,None,NaN,28.24
21,21,tonycao312@gmail.com,03724918520372491852,"[None, None, None]","[SQL, Framework, Software Engineering, library, software, .NET, PHP, C, Android, CSS, ASP.NET, Design, HTML]",[[and gain more experience in a positive environment.. EDUCA TION.]],University,NaN,27.58
16,16,Cityvothanhnam18092001@gmail.com,039-252-5473,"[github.com/Thanh-Nam-1809github.com/Thanh-Nam-1809, None, None]","[JavaScript, Github, PHP, CSS, Mobile, HTML, play, Node JS]",None,None,NaN,27.57
11,11,nghiaapag@gmail.com,0977949890,"[None, None, None]","[SQL, MYSQL, Visual basic, COMMERCE, Database, Computer Science, CSS, Ajax, Certificate, Wordpress, C++, Laravel, Sublime Text, HTML, Visual Studio, Framework, MySQL, Jquery, libraries, PHP, support, Java, Server, JSON, play]",None,None,NaN,26.52
14,14,vhduy23@gmail.com,None,"[github.com/vhduy23github.com/vhduy23, None, None]","[SQL, Ecommerce, API, Git, Jquery, Github, .NET, database, Javascript, Database, PHP, R, CSS, C, github, SOFTWARE, HTML]",None,University,NaN,25.98
26,26,lephongplus2016@gmail.com,0372546237,"[github.com/lephongplus201., None, None]","[Mongodb, database design, MySQL, Git, API, MySql, web app, Database, PHP, Google, Computer science, MongoDB]",None,None,NaN,25.64
13,13,phananhnhat0812@gmail.com,0908631492,"[github.com/AnhNhat111, None, None]","[Laravel, framework, Flutter, database design, API, Angular, Languages, Javascript, PHP, Mysql]",[[I want t o gain a lot of knowledge and experience in PHP.]],None,NaN,19.87
7,7,enanhphu1911@gmail.com,0738421397,"[github.com/Nguygithub.com/Nguygithub.com/Nguy, None, None]","[Laravel, SQL, MySQL, PHP, C, CSS, github, HTML]",[[The accumulated pr actical work experience will be the basis for achie ving the. goal of becoming a good pr ogrammer in the futur e..]],None,NaN,17.96
15,15,vuhongthien18@gmail.com,0398073470,"[github.com/vuhongthien., None, None]","[SQL, Framework, FRAMEWORK, MySQL, Languages, Databases, Spring Boot, SPRING, PHP, C, Ajax, CSS, Design, HTML, Programming language]",None,None,NaN,17.22
23,23,an2703201@gmail.com,0377421240,"[None, None, None]","[design, Laravel, Framework, MySQL, Angular, Git, Database, PHP, CSS, GitHub]",None,None,NaN,16.84
28,28,lethevinh1997@gmail.comv89@example.nethiep.chuong@example.comintron.0x@icloud.com,0586801768,"[github.com/mian17github.com/mian17github.com/mian17github.com/mian17, None, None]","[React, JavaScript, CERTIFICATE, COMMERCE, Database, CSS, PROGRAMMING LANGUAGE, Pusher, React Router, C, languages, MacOS, Laravel, Source code, Design, HTML, MariaDB, MySQL, Git, Ubuntu, PHP, GitHub, Bootstrap]",None,"UNIVERSITY OF SOCIAL SCIENCES & HUMANITIES, HCMCCERTIFICATIONS",NaN,13.45
4,4,caonhatkhang2001@gmail.com,0889066088,"[github.com/nhatkhangcaogithub.com/nhatkhangcaogithub.com/nhatkhangcao., None, None]","[robot, MySQL, Git, Github, Javascript, Database, PHP, CSS, Computer Engineering, arduino]",None,None,NaN,12.42
24,24,envu191000@gmail.com,0914684169,"[github.com/nguygithub.com/nguygithub.com/nguy, None, None]","[API, CSS, HTML, Programming language, MongoDB]",None,None,NaN,11.23
8,8,nguyentrinhhoangphuong@gmail.com,0788565437,"[github.com/hoangphuong965github.com/hoangphuong965github.com/hoangphuong965, None, None]","[Laravel, React, MySQL, Github, PHP, CSS, github, HTML]",None,None,NaN,11.07
12,12,quocmanh1998s@gmail.com,0826572751,"[github.com/quocmanh98github.com/quocmanhh99github.com/quocmanh98, None, None]","[Laravel, Framework, MYSQL, JavaScript, API, Github, database, Postman, Database, PHP, CSS, Ajax, source code, Design, HTML, Bootstrap]",None,None,NaN,5.70
18,18,tinh.vtq@kissyo.edu.vn,0972277754,"[github.com/vchie.github.com/vchieu7301, None, linkedin.com/in/chi.]","[Laravel, SQL, Framework, framework, MySQL, Visual Studio Code, Github, Javascript, PHP, C, CSS, HTML, Server]",None,None,NaN,4.32
10,10,namtanbinh0147@gmail.com,0934697602,"[github.com/TanBinhNam., None, None]","[Laravel, JQuery, Framework, MySQL, Javascript, Database, PHP, CSS, HTML]",None,None,NaN,3.54
29,29,hp205125@gmail.com,0853736682,"[github.com/Manghongphuonggithub.com/Manghongphuong, None, None]","[SQL, jQuery, MySQL, Angular, JavaScript, Github, PHP]",None,None,NaN,3.25
22,22,dangquangminhdn86@gmail.com,0898479840,"[github.com/dangquangmi., None, None]","[SQL, Angular, PHP, CSS, angular, HTML]",None,None,NaN,3.03
5,5,None,084531 1020,"[github.com/cass.github.com/cassle123github.com/cassle123github.com/cassle123github.com/cassle123github.com/cassle123, None, None]","[SQL, Laravel, ExpressJS, MySQL, VueJS, Google Maps, API, Socket.io, Github, Android Studio, Javascript, Database, PHP, Google, CSS, source code, HTML, Server]",None,None,NaN,2.04
9,9,nguyenkhai250419@gmail.com,0973548264,"[None, None, None]","[SQL, MySQL, Visual Studio Code, Javascript, Database, ASP.NET, C, CSS, PHP, HTML, Server]",None,None,NaN,1.87
25,25,hovi2711@gmail.com,0899385753,"[github.com/viho1906github.com/viho1906, None, None]","[MySQL, Angular, VueJS, Vuejs, ES6, PHP, C, CSS, HTML, Wordpress, MongoDB]",None,None,NaN,1.60
19,19,xsang1317@gmail.com,0934101207,"[None, None, None]","[MYSQL, API, Angular, MySQL, Visual Studio Code, database, Google, PHP, CSS]",None,None,NaN,1.30
2,2,huynhthithuydung2707@gmail.com,0934147908,"[None, None, None]","[Visual Studio, SQL, PHP, MySQL]",None,None,NaN,0.59
0,0,htran9776@gmail.com,0972902961,"[None, None, None]","[AVA, SQL, C, MySQL]",None,None,NaN,0.00